In [1]:
import numpy as np
from matplotlib import pyplot as plt


## Ejercicio 1

En este ejercicio vamos a probar o refutar algunas propiedades sobre el numero de condicion.
En cada item tendremos un propiedad que puede ser verdadera o falsa.
 - En caso de ser verdadera: dar su demostracion.
 - En caso de ser falsa: utilizar numpy para dar un contraejemplo.

Utilizar el comando `np.linalg.cond`.

**(a)** $Cond_2(A)$ + $Cond_2(B)$ = $Cond_2(A+B)$

In [ ]:
A = np.diag([1,2,3,4]) + np.diag([1,2,3],1) + np.diag([2,3,4],-1)

B = np.diag([1,5,3,1]) + np.diag([4,6,3],1)


In [ ]:
print(np.linalg.cond(A,2) + np.linalg.cond(B,2))
print(np.linalg.cond(A + B,2))

#Nada que ver, es falsa

61.82968256470035
22.722792530338825


**(b)** $Cond_1(A)$ - $Cond_1(B)$ = $Cond_2(A-B)$


In [ ]:
print(np.linalg.cond(A,1) - np.linalg.cond(B,1))
print(np.linalg.cond(A-B,2))

#Nada que ver tampoco

-45.0
2.8712800141334492e+16


**(c)** $Cond_2(A)$ * $Cond_2(B)$ = $Cond_2(A.B)$

In [ ]:

print(np.linalg.cond(A,2) * np.linalg.cond(B,2))
print(np.linalg.cond(A*B,2))

676.0336226001485
31.36583616478391


## Ejercicio 2


El objetivo de este ejercicio es estudiar el número de condición de
algunas matrices a medida que su tamaño aumenta.


**(a)** Programar funciones que, dado $n \in \mathbb{N}$, devuelvan las siguientes matrices de $\mathbb{R}^{n\times n}$. La función que define $B_n$ ya viene dada.


\begin{equation*}
A_n=
\begin{pmatrix}
\frac{1}{n} & 0 & 0 & \cdots  & n^2\\
0 & \frac{1}{n} & 0 & \cdots & 0 \\
0 & 0 & \frac{1}{n} & \cdots & 0\\
\vdots & \vdots & \vdots  & \ddots & \vdots\\
1 & 0 & 0 & \cdots &  \frac{1}{n}\\
\end{pmatrix}
\qquad
B_n=
\begin{pmatrix}
4 & 1 & 0 & \cdots & 0 & 0\\
1 & 4 & 1 & \cdots & 0 & 0 \\
0 & 1 & 4 & \ddots &  & \vdots\\
\vdots & \vdots & \ddots & \ddots & \ddots & \vdots \\
0 & 0 &  & \ddots & 4 & 1\\
0 & 0 & \cdots & \cdots & 1 & 4 \\
\end{pmatrix}
\qquad
H_n=
\begin{pmatrix}
1 & \frac{1}{2} & \frac{1}{3} & \cdots  & \frac{1}{n}\\
\frac{1}{2} & \frac{1}{3} & \frac{1}{4} & \cdots & \frac{1}{n+1} \\
\frac{1}{3} & \frac{1}{4} & \frac{1}{5} & \cdots & \frac{1}{n+2}\\
\vdots & \vdots & \vdots  & \ddots & \vdots\\
\frac{1}{n} & \frac{1}{n+1} & \frac{1}{n+2} & \cdots &  \frac{1}{2n-1}\\
\end{pmatrix}
\end{equation*}



**Sugerencia:** Utilizar la función `np.diag` que recibe un array de números y genera una matriz diagonal con elementos dados por el array. (La usamos la semana pasada)




In [7]:
def A_n(n):

  A = np.diag((1/n)*np.ones(n))

  # Asignar un número (por ejemplo, 7) en la esquina superior derecha
  A[0, -1] = n**2
  A[-1, 0] = 1

  return A


def B_n(n):

  B = np.diag(4*np.ones(n)) + np.diag(np.ones(n-1),-1) + np.diag(np.ones(n-1),1)

  return B


def H_n(n):
  #creo las columnas, y después creo la matriz a partir de ellas
    
  vectores = []

  for m in range(n):
    vec = np.array([])

    for i in range(1+m,n+1+m):
      vec = np.append(vec, 1/i)
  
    vectores.append(vec)

  H = np.column_stack(vectores)

  return H
  

#print(H_n(3))

# Ej 5, c  
(de la guía)

In [17]:
A = np.array([[3,0,0],[0,5/4,3/4],[0,3/4,5/4]])

print(np.linalg.cond(A,2))
print(np.linalg.cond(A,np.inf))



6.000000000000002
6.0


In [88]:
b = np.array([3,2,2])
x = [1,1,1]

a = 1/6 * 10e-4  * np.linalg.norm(b,2)


delta_b =  np.random.random(3)

#normalizamos

delta_b = (delta_b/np.linalg.norm(delta_b,2)) * np.abs(a)

print(delta_b)

# vemos que las soluciones se parecen a la exacta, x = (1,1,1)

solución = np.linalg.solve(A,b + delta_b)

print(solución)

print(np.linalg.norm(x - solución,2))


[0.00047265 0.00031218 0.00038906]
[1.00015755 1.00009844 1.00025218]
0.00031322250112441214


Y todas las soluciones tienen errores menores a 10-4!!

# Ejercicio 11

Primero quiero hacer unas funciones que hagan sustitución forward y backwards dadas una matriz triangular inferior o superior

In [28]:
L = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3], [4,4,4,4]])

print(L)

print(L[3, 0:3])

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
[4 4 4]


In [30]:
x = np.array([1,1,1,1,1])


array([1, 1])

In [68]:
def sustitución_hacia_adelante(L, b):
    
    n = len(L) #filas
    m = len(L.T) # columnas


    if n != m:
        print("La matriz no es cuadrada")

    if n == m:
        if np.linalg.norm(np.triu(L,k=1)) != 0:
            print("La matriz no es triangular inferior")
        else:
            if np.any(np.diag(L)==0): #True si hay algún cero en la diagonal
                print("La matriz tiene uno o más ceros en la diagonal --> si es triangular inferior, no es inversible")

            else: # resolvemos el sistema

                x = np.ones(n)

                x[0]=b[0] / L[0,0]

                for k in range(1,n):
                    x[k] = (b[k] - L[k, 0:k] @ x[0:k]) / L[k,k]


                return x


In [69]:
L = np.array([[1,0,0,0],
             [3,2,0,0],
             [1,1,1,0],
             [1,1,1,1]])

b = np.array([1,0,0,0]) 

x = sustitución_hacia_adelante(L, b)

print(x)

a = np.linalg.solve(L, b)

print(a)

[ 1.  -1.5  0.5  0. ]
[ 1.  -1.5  0.5  0. ]


In [70]:

def sustitución_hacia_atrás(U, b):
    
    n = len(U) #filas
    m = len(U.T) # columnas


    if n != m:
        print("La matriz no es cuadrada")

    if n == m:
        if np.linalg.norm(np.tril(U,k=-1)) != 0:
            print("La matriz no es triangular superior")
        
        else:
            if np.any(np.diag(U)==0): #True si hay algún cero en la diagonal
                print("La matriz tiene uno o más ceros en la diagonal --> si es triangular superior, no es inversible")

            else: # resolvemos el sistema

                x = np.ones(n)

                x[n-1]=b[n-1] / U[n-1,n-1]

                for k in range(n-2,-1,-1):
                    x[k] = (b[k] - U[k, k+1:n] @ x[k+1:n]) / U[k,k]


                return x



In [72]:
U = np.array([[1,1,0,1],
             [0,2,1,1],
             [0,0,1,1],
             [0,0,0,1]])

b = np.array([1,2,1,1]) 

x = sustitución_hacia_atrás(U, b)

print(x)

a = np.linalg.solve(U, b)

print(a)

[-0.5  0.5  0.   1. ]
[-0.5  0.5  0.   1. ]


In [112]:
# Ahora quiero, dada una matriz A, calcular una descomposición LU usando las matrices de Gauss

# La U va a ser la matriz triangulada, y la L, van a ser el producto de las inversas de todas las matrices de gauss usadas para triangular A


A = np.array([[1,1,0,1],
              [0,2,1,1],
              [3,0,1,1],
              [0,0,0,1]],dtype=float)


#Importantísimo aclarar que A es float!! Sino me terminaba redondeando A en algunos pasos y daba mal

n = len(A)

taus = [] # los voy guardando para después armarme la matriz L

for k in range(0,n - 1):   #son n-1 pasos, arranca en 0 (arrancamos a triangular desde la 2da fila)
    
    if A[k,k] == 0:  # Condición de pivote cero: si A[k,k] es 0, deberíamos hacer un intercambio de filas
        print(f"Advertencia: Pivote cero encontrado en k={k}. Se requiere intercambio de filas.")
        break # Detener

    tau = np.zeros(n)
    tau[k+1:n] = A[k+1:n,k] / A[k,k]


    A[k+1:n, : ] = A[k+1:n, : ] - np.outer(tau[k+1:n], A[k,:])

    taus.append(tau)
    

print(A)
print(np.column_stack(taus))


U = A

#para construir la matriz L, esta tiene que tener unos en la diagonal. Como taus hay n-1 (ya que hay n-1 pasos), me falta una columna para armarme la L.
#entonces apendexeo un vector de ceros al final, y después le sumo la identidad para obtener L

taus.append(np.zeros(n))

L = np.column_stack(taus) + np.diag(np.ones(n))

print(L)


print(L @ A)


[[ 1.   1.   0.   1. ]
 [ 0.   2.   1.   1. ]
 [ 0.   0.   2.5 -0.5]
 [ 0.   0.   0.   1. ]]
[[ 0.   0.   0. ]
 [ 0.   0.   0. ]
 [ 3.  -1.5  0. ]
 [ 0.   0.   0. ]]
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 3.  -1.5  1.   0. ]
 [ 0.   0.   0.   1. ]]
[[1. 1. 0. 1.]
 [0. 2. 1. 1.]
 [3. 0. 1. 1.]
 [0. 0. 0. 1.]]


Creo la función para que, dada A con elementos en la diagonal no nula, devuelva L y U sin pivoteo

Hay que setear la aritmética a usar, o sea los 

In [115]:
def LU_sin_pivoteo(A):

    A = np.array(A, dtype=float)

    n = len(A)

    taus = [] 

    for k in range(0,n - 1): 
        
        if A[k,k] == 0: 
            print(f"Advertencia: Pivote cero encontrado en k={k}. Se requiere intercambio de filas.")
            break # Detener

        tau = np.zeros(n)
        tau[k+1:n] = A[k+1:n,k] / A[k,k]

        A[k+1:n, : ] = A[k+1:n, : ] - np.outer(tau[k+1:n], A[k,:])

        taus.append(tau)

    U = A

    taus.append(np.zeros(n))
    L = np.column_stack(taus) + np.diag(np.ones(n))

    return L, U



In [119]:
A = np.array([[1,1,0,1],
              [0,2,1,1],
              [3,0,1,1],
              [0,0,0,1]])


L, U = LU_sin_pivoteo(A)


print(L@U)

[[1. 1. 0. 1.]
 [0. 2. 1. 1.]
 [3. 0. 1. 1.]
 [0. 0. 0. 1.]]


In [118]:

def resolver(A,b):
    # Para un sistema lineal con su matriz sin ceros en la diagonal
    #sin pivoteo

    L, U = LU_sin_pivoteo(A)

    eta = sustitución_hacia_adelante(L, b)

    x = sustitución_hacia_atrás(U,eta)

    return x


In [122]:
A = np.array([[1,1,0,1],
              [0,2,1,1],
              [3,0,1,1],
              [0,0,0,1]])

b = np.array([1,2,1,2])

sol = np.linalg.solve(A, b)
print(sol)

sol_mía = resolver(A,b)
print(sol_mía)


[-0.6 -0.4  0.8  2. ]
[-0.6 -0.4  0.8  2. ]


Se puede obtener la inversa de la matriz A, es resolver unos sistemas lineales, pero como no lo vimos en la teórica y no tengo tiempo no lo hago  

Iba a hacer el sistema con pivoteo, pero creo que en la práctica no lo hicieron... si tengo tiempo después lo hago